[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libopus-dev:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libopus-dev:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH",
]

[target.i686-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libopus-dev:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH",
]

[target.aarch64-apple-darwin]
pre-build = ["brew install opus"]

[target.x86_64-apple-darwin]
pre-build = ["brew install opus"]
