name: nightly
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: add nightly suffix to version
        run: sed -e '/plugin_version=.*/s/$/-nightly.${{ github.sha }}/' -i gradle.properties

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: get version
        id: version
        run: echo "version=$(grep plugin_version gradle.properties | sed -e "s/    plugin_version=//g")" >> $GITHUB_OUTPUT

      - name: upload fabric artifact
        uses: actions/upload-artifact@v3
        with:
          name: voicechat-discord-fabric-nightly.jar
          path: fabric/build/libs/voicechat-discord-fabric-${{ steps.version.outputs.version }}.jar

      - name: upload paper artifact
        uses: actions/upload-artifact@v3
        with:
          name: voicechat-discord-paper-nightly.jar
          path: paper/build/libs/voicechat-discord-paper-${{ steps.version.outputs.version }}.jar
